name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Lint
        uses: astral-sh/ruff-action@v3
        with:
          src: "src"

      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
          src: "src"

  test-python-package:
    needs: lint-python-package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

      - name: Prune cache
        run: uv cache prune --ci
